[package]
name = "sox"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.7"
bincode = "1.3.3"
bs58 = "0.4.0"
jsonrpsee = { version = "0.22.5", features = [
  "http-client",
  "macros",
  "server",
] }
jsonrpc-core = "18.0.0"
log = "0.4.27"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-account-decoder = "2.2"
solana-rpc-client-api = "2.2"
solana-sdk = "2.2"
solana-transaction-status = "2.2"
thiserror = "2.0.12"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
env_logger = "0.11.8"
rand = "0.9.1"
solana-rpc-client = "2.2"
